// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Transaction provides a mock function with given fields: fn
func (_m *MockClient) Transaction(fn func(*MockClient) error) error {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*MockClient) error) error); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockClient_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - fn func(C) error
func (_e *MockClient_Expecter) Transaction(fn interface{}) *MockClient_Transaction_Call {
	return &MockClient_Transaction_Call{Call: _e.mock.On("Transaction", fn)}
}

func (_c *MockClient_Transaction_Call) Run(run func(fn func(*MockClient) error)) *MockClient_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(*MockClient) error))
	})
	return _c
}

func (_c *MockClient_Transaction_Call) Return(_a0 error) *MockClient_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Transaction_Call) RunAndReturn(run func(func(*MockClient) error) error) *MockClient_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
