// Code generated by mockery v2.39.2. DO NOT EDIT.

package mocks

import (
	interfaces "clone/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository[T interface{}, C interfaces.Client[C]] struct {
	mock.Mock
}

type MockRepository_Expecter[T interface{}, C interfaces.Client[C]] struct {
	mock *mock.Mock
}

func (_m *MockRepository[T, C]) EXPECT() *MockRepository_Expecter[T, C] {
	return &MockRepository_Expecter[T, C]{mock: &_m.Mock}
}

// Clone provides a mock function with given fields: client
func (_m *MockRepository[T, C]) Clone(client C) T {
	ret := _m.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 T
	if rf, ok := ret.Get(0).(func(C) T); ok {
		r0 = rf(client)
	} else {
		r0 = ret.Get(0).(T)
	}

	return r0
}

// MockRepository_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockRepository_Clone_Call[T interface{}, C interfaces.Client[C]] struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - client C
func (_e *MockRepository_Expecter[T, C]) Clone(client interface{}) *MockRepository_Clone_Call[T, C] {
	return &MockRepository_Clone_Call[T, C]{Call: _e.mock.On("Clone", client)}
}

func (_c *MockRepository_Clone_Call[T, C]) Run(run func(client C)) *MockRepository_Clone_Call[T, C] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(C))
	})
	return _c
}

func (_c *MockRepository_Clone_Call[T, C]) Return(_a0 T) *MockRepository_Clone_Call[T, C] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Clone_Call[T, C]) RunAndReturn(run func(C) T) *MockRepository_Clone_Call[T, C] {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: fn
func (_m *MockRepository[T, C]) Transaction(fn func(C) error) error {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(C) error) error); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockRepository_Transaction_Call[T interface{}, C interfaces.Client[C]] struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - fn func(C) error
func (_e *MockRepository_Expecter[T, C]) Transaction(fn interface{}) *MockRepository_Transaction_Call[T, C] {
	return &MockRepository_Transaction_Call[T, C]{Call: _e.mock.On("Transaction", fn)}
}

func (_c *MockRepository_Transaction_Call[T, C]) Run(run func(fn func(C) error)) *MockRepository_Transaction_Call[T, C] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(C) error))
	})
	return _c
}

func (_c *MockRepository_Transaction_Call[T, C]) Return(_a0 error) *MockRepository_Transaction_Call[T, C] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Transaction_Call[T, C]) RunAndReturn(run func(func(C) error) error) *MockRepository_Transaction_Call[T, C] {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository[T interface{}, C interfaces.Client[C]](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository[T, C] {
	mock := &MockRepository[T, C]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
